### ISSUE TITLE
Error: Invalid Response URL

### ISSUE THREAD

**Issue by jelenavicic** [dvanoni/notero#66]
Hello,

Sync to Notion is failing when I try to save items to my Zotero database. This is the error: APIResponseError: Invalid request URL. Could you please advise on how to solve it?

<img width="267" alt="Screen Shot 2022-04-22 at 7 29 27 AM" src="https://user-images.githubusercontent.com/54126683/164736809-ae732dd8-5906-4b64-89d2-b4af40db2fa6.png">

And thank you so much for developing this plugin - if I can get it to work for me, it might be a game changer.

For reference, I am using Chrome version 100.0.4896.127 (Official Build) (x86_64), Zotero version 6.0.5.

Thanks in advance!

**Comment by dvanoni** [comment]
Hi @jelenavicic, thanks for reaching out! By chance, are you running into the same issue that was resolved in #62?

**Comment by jelenavicic** [comment]
Hi @dvanoni, thank you for your help! It looks like I did run into the same issue. I had it fixed, but unfortunately Zotero database is still not syncing with Notion.

**Comment by jelenavicic** [comment]
I finally got it to work today! For some reason it was not syncing with the original collection I assigned, but when I created a collection in a different group, it synced right away! One of the possible reasons for not syncing was a lack of space, but it failed to sync with that first collection even after I updated my Zotero plan to get more storage. Anyways, it's all working now!
